import { supabase } from './supabase';
import { servicesData, staffData, customersData, shopInfo, scheduleData } from '../data/mock';
import { 
  cacheAppointmentsLocally, 
  getCachedAppointmentsLocally 
} from './offlineDb';
import { getActiveOwnerAndShopIds } from './ownerDashboardRepository';


// Mock IDs generated by the SQL script for initial setup
const SHOP_ID = '22222222-2222-2222-2222-222222222222';
const PROFILE_ID = '11111111-1111-1111-1111-111111111111';

// In-memory fallback stores
let localAppointments = [...scheduleData.map(s => ({
  id: String(s.id),
  shop_id: SHOP_ID,
  customer_name: s.customer,
  customer_phone: "+91 9876543210",
  service_name: s.service,
  staff_name: s.staff,
  date: "Today",
  time: s.time,
  status: s.status,
  price: parseFloat(s.amount.replace(/[^0-9.]/g, '')) || 500,
  created_at: new Date().toISOString()
}))];

let localServices = [...servicesData.map(s => ({
  id: String(s.id),
  shop_id: SHOP_ID,
  name: s.name,
  category: s.category,
  duration: parseInt(s.duration) || 30,
  price: parseFloat(s.price.replace(/[^0-9.]/g, '')) || 0,
  discount_price: s.discount ? parseFloat(s.discount.replace(/[^0-9.]/g, '')) : null,
  is_active: s.active,
  created_at: new Date().toISOString()
}))];


let localCustomers = [...customersData.map(c => ({
  id: String(c.id),
  shop_id: SHOP_ID,
  name: c.name,
  mobile: c.mobile,
  email: c.email || `${c.name.toLowerCase().replace(/\s+/g, '.')}@example.com`,
  visits: c.visits,
  spent: c.spent,
  lastVisit: c.lastVisit,
  status: c.status,
  avatar_url: c.avatar,
  created_at: new Date().toISOString()
}))];

let localStaff = [...staffData.map(st => ({
  id: String(st.id),
  shop_id: SHOP_ID,
  name: st.name,
  role: st.role,
  rating: parseFloat(st.rating) || 5.0,
  status: st.status,
  avatar_url: st.avatar,
  created_at: new Date().toISOString()
}))];

const loadFromLocalStorage = (key: string, defaultValue: any) => {
  try {
    const val = localStorage.getItem(key);
    return val ? JSON.parse(val) : defaultValue;
  } catch {
    return defaultValue;
  }
};

const saveToLocalStorage = (key: string, value: any) => {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error(e);
  }
};

let localShop = loadFromLocalStorage('nexora_local_shop', {
  id: SHOP_ID,
  name: shopInfo.name,
  status: shopInfo.status,
  category: "Salon & Spa",
  phone: "+91 9610360360",
  email: "owner@royalglow.com",
  address: "123 High Street, Bandra West, Mumbai",
  email_notifications_enabled: true,
  created_at: new Date().toISOString()
});

let localProfile = loadFromLocalStorage('nexora_local_profile', {
  id: PROFILE_ID,
  full_name: shopInfo.owner.name,
  email: "owner@royalglow.com",
  avatar_url: shopInfo.owner.avatar,
  role: "Shop Owner"
});

export const isSupabaseConfigured = () => {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (!url || !key) return false;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
};

export const api = {
  // File Upload
  async uploadFile(file: File, folder: string) {
    if (!isSupabaseConfigured()) {
      return URL.createObjectURL(file);
    }
    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${Math.random().toString(36).substring(2, 15)}.${fileExt}`;
      const filePath = `${folder}/${fileName}`;
      const { error } = await supabase.storage.from('salon-assets').upload(filePath, file);
      if (error) throw error;
      const { data } = supabase.storage.from('salon-assets').getPublicUrl(filePath);
      return data.publicUrl;
    } catch {
      return URL.createObjectURL(file);
    }
  },

  async uploadToBucket(file: File, bucketName: string, userId: string) {
    if (!isSupabaseConfigured()) {
      return URL.createObjectURL(file);
    }
    try {
      const allowedExts = ['jpg', 'jpeg', 'png', 'webp'];
      const fileExt = file.name.split('.').pop()?.toLowerCase() || '';
      if (!allowedExts.includes(fileExt)) {
        throw new Error('Only jpg, jpeg, png, and webp are allowed.');
      }
      const randomUuid = Math.random().toString(36).substring(2, 15);
      const filePath = `${userId}/${randomUuid}-${file.name}`;
      
      const { error } = await supabase.storage.from(bucketName).upload(filePath, file);
      if (error) {
        console.warn(`Upload to bucket ${bucketName} failed, trying salon-assets fallback:`, error);
        // Fallback to 'salon-assets' bucket
        const { error: fallbackError } = await supabase.storage.from('salon-assets').upload(filePath, file);
        if (fallbackError) throw fallbackError;
        const { data } = supabase.storage.from('salon-assets').getPublicUrl(filePath);
        return data.publicUrl;
      }
      const { data } = supabase.storage.from(bucketName).getPublicUrl(filePath);
      return data.publicUrl;
    } catch (err) {
      console.error('File upload failed:', err);
      return URL.createObjectURL(file);
    }
  },

  // Appointments / Schedule (Offline & Online Sync)
  async getAppointments(shopId?: string) {
    let targetShopId = shopId;
    if (!targetShopId) {
      const activeIds = await getActiveOwnerAndShopIds();
      targetShopId = activeIds.shopId;
    }

    if (!isSupabaseConfigured()) {
      // Always store/cache locally in IndexedDB as well
      await cacheAppointmentsLocally(localAppointments as any);
      return localAppointments;
    }
    try {
      const { data, error } = await supabase
        .from('appointments')
        .select(`
          *,
          services(id, name, price, discounted_price, duration_minutes),
          staff(id, full_name, primary_role),
          customers(id, full_name, mobile_number, email),
          profiles(id, full_name, phone, email)
        `)
        .eq('shop_id', targetShopId)
        .order('created_at', { ascending: false });

      if (error) {
        // Try fallback query without relations if foreign keys/relations fail
        const { data: simpleData, error: simpleErr } = await supabase
          .from('appointments')
          .select('*')
          .eq('shop_id', targetShopId)
          .order('created_at', { ascending: false });
        if (simpleErr) throw simpleErr;
        const result = simpleData || [];
        await cacheAppointmentsLocally(result as any);
        return result;
      }

      const result = data || [];
      // Cache fetched schedule in IndexedDB for offline access
      await cacheAppointmentsLocally(result as any);
      return result;
    } catch (err) {
      console.warn('Network issue fetching appointments with relations, trying simple select or offline IndexedDB:', err);
      try {
        const { data: simpleData, error: simpleErr } = await supabase
          .from('appointments')
          .select('*')
          .eq('shop_id', targetShopId)
          .order('created_at', { ascending: false });
        if (!simpleErr && simpleData) {
          await cacheAppointmentsLocally(simpleData as any);
          return simpleData;
        }
      } catch (fallbackErr) {
        // ignore
      }
      const offlineCached = await getCachedAppointmentsLocally();
      return offlineCached;
    }
  },

  async addAppointment(appointment: any, shopId?: string) {
    let targetShopId = shopId;
    if (!targetShopId) {
      const activeIds = await getActiveOwnerAndShopIds();
      targetShopId = activeIds.shopId;
    }

    const newAppt = {
      ...appointment,
      id: appointment.id || String(Date.now()),
      shop_id: targetShopId,
      created_at: new Date().toISOString()
    };

    if (!isSupabaseConfigured()) return newAppt;

    try {
      const { data, error } = await supabase
        .from('appointments')
        .insert([newAppt])
        .select()
        .single();
      if (error) throw error;
      return data;
    } catch (err) {
      console.warn('Saved appointment offline locally:', err);
      return newAppt;
    }
  },

  async updateAppointmentStatus(id: string, status: string) {
    localAppointments = localAppointments.map(a => a.id === id ? { ...a, status } : a);
    await cacheAppointmentsLocally(localAppointments as any);

    if (!isSupabaseConfigured()) return;

    try {
      await supabase.from('appointments').update({ status }).eq('id', id);
    } catch (err) {
      console.warn('Updated status offline in IndexedDB:', err);
    }
  },

  async updateAppointment(id: string, appointment: any) {
    localAppointments = localAppointments.map(a => a.id === id ? { ...a, ...appointment } : a);
    await cacheAppointmentsLocally(localAppointments as any);

    if (!isSupabaseConfigured()) return localAppointments.find(a => a.id === id) || appointment;

    try {
      const { data, error } = await supabase.from('appointments').update(appointment).eq('id', id).select().single();
      if (error) throw error;
      return data;
    } catch {
      return localAppointments.find(a => a.id === id) || appointment;
    }
  },

  async deleteAppointment(id: string) {
    localAppointments = localAppointments.filter(a => a.id !== id);
    await cacheAppointmentsLocally(localAppointments as any);

    if (!isSupabaseConfigured()) return;

    try {
      await supabase.from('appointments').delete().eq('id', id);
    } catch {
      // fallback handled
    }
  },

  async bulkDeleteAppointments(ids: string[]) {
    localAppointments = localAppointments.filter(a => !ids.includes(a.id));
    await cacheAppointmentsLocally(localAppointments as any);

    if (!isSupabaseConfigured()) return;

    try {
      await supabase.from('appointments').delete().in('id', ids);
    } catch {
      // fallback handled
    }
  },

  async bulkUpdateAppointmentsStatus(ids: string[], status: string) {
    localAppointments = localAppointments.map(a => ids.includes(a.id) ? { ...a, status } : a);
    await cacheAppointmentsLocally(localAppointments as any);

    if (!isSupabaseConfigured()) return;

    try {
      await supabase.from('appointments').update({ status }).in('id', ids);
    } catch {
      // fallback handled
    }
  },


  // Services
  async getServices(shopId?: string) {
    let targetShopId = shopId;
    if (!targetShopId) {
      const activeIds = await getActiveOwnerAndShopIds();
      targetShopId = activeIds.shopId;
    }

    if (!isSupabaseConfigured()) return localServices;
    try {
      const { data, error } = await supabase.from('services').select('*').eq('shop_id', targetShopId).order('created_at', { ascending: false });
      if (error) throw error;
      return data || [];
    } catch {
      return [];
    }
  },
  async addService(service: any, shopId?: string) {
    let targetShopId = shopId || (await getActiveOwnerAndShopIds()).shopId;
    
    if (!isSupabaseConfigured()) {
      const newSvc = { ...service, id: String(Date.now()), shop_id: targetShopId, created_at: new Date().toISOString() };
      return newSvc;
    }
    try {
      const { data, error } = await supabase.from('services').insert([{ ...service, shop_id: targetShopId }]).select().single();
      if (error) throw error;
      return data;
    } catch {
      const newSvc = { ...service, id: String(Date.now()), shop_id: targetShopId, created_at: new Date().toISOString() };
      return newSvc;
    }
  },
  async updateService(id: string, service: any) {
    if (!isSupabaseConfigured()) {
      localServices = localServices.map(s => s.id === id ? { ...s, ...service } : s);
      return localServices.find(s => s.id === id) || service;
    }
    try {
      const { data, error } = await supabase.from('services').update(service).eq('id', id).select().single();
      if (error) throw error;
      return data;
    } catch {
      localServices = localServices.map(s => s.id === id ? { ...s, ...service } : s);
      return localServices.find(s => s.id === id) || service;
    }
  },
  async deleteService(id: string) {
    localServices = localServices.filter(s => s.id !== id);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('services').delete().eq('id', id);
    } catch {
      // fallback handled
    }
  },
  async bulkDeleteServices(ids: string[]) {
    localServices = localServices.filter(s => !ids.includes(s.id));
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('services').delete().in('id', ids);
    } catch {
      // fallback handled
    }
  },
  async bulkUpdateServicesStatus(ids: string[], isActive: boolean) {
    localServices = localServices.map(s => ids.includes(s.id) ? { ...s, is_active: isActive } : s);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('services').update({ is_active: isActive }).in('id', ids);
    } catch {
      // fallback handled
    }
  },
  async bulkUpdateServices(updates: Array<{ id: string; price?: number; discount_price?: number | null; duration?: number; category?: string; is_active?: boolean }>) {
    const updateMap = new Map(updates.map(u => [u.id, u]));
    localServices = localServices.map(s => {
      const u = updateMap.get(s.id);
      return u ? { ...s, ...u } : s;
    });

    if (!isSupabaseConfigured()) return localServices;

    try {
      await Promise.all(updates.map(u => {
        const { id, ...data } = u;
        return supabase.from('services').update(data).eq('id', id);
      }));
      return localServices;
    } catch {
      return localServices;
    }
  },

  // Customers
  async getCustomers() {
    if (!isSupabaseConfigured()) return localCustomers;
    try {
      const { data, error } = await supabase.from('customers').select('*').eq('shop_id', SHOP_ID).order('created_at', { ascending: false });
      if (error) throw error;
      return (data && data.length > 0) ? data : localCustomers;
    } catch {
      return localCustomers;
    }
  },
  async addCustomer(customer: any) {
    if (!isSupabaseConfigured()) {
      const newCust = {
        ...customer,
        id: String(Date.now()),
        shop_id: SHOP_ID,
        visits: 0,
        spent: "₹0",
        lastVisit: "New Customer",
        status: customer.status || "Regular",
        avatar_url: customer.avatar_url || `https://i.pravatar.cc/150?u=${Date.now()}`,
        created_at: new Date().toISOString()
      };
      localCustomers = [newCust, ...localCustomers];
      return newCust;
    }
    try {
      const { data, error } = await supabase.from('customers').insert([{ ...customer, shop_id: SHOP_ID }]).select().single();
      if (error) throw error;
      return data;
    } catch {
      const newCust = {
        ...customer,
        id: String(Date.now()),
        shop_id: SHOP_ID,
        visits: 0,
        spent: "₹0",
        lastVisit: "New Customer",
        status: customer.status || "Regular",
        avatar_url: customer.avatar_url || `https://i.pravatar.cc/150?u=${Date.now()}`,
        created_at: new Date().toISOString()
      };
      localCustomers = [newCust, ...localCustomers];
      return newCust;
    }
  },
  async updateCustomer(id: string, customer: any) {
    if (!isSupabaseConfigured()) {
      localCustomers = localCustomers.map(c => c.id === id ? { ...c, ...customer } : c);
      return localCustomers.find(c => c.id === id) || customer;
    }
    try {
      const { data, error } = await supabase.from('customers').update(customer).eq('id', id).select().single();
      if (error) throw error;
      return data;
    } catch {
      localCustomers = localCustomers.map(c => c.id === id ? { ...c, ...customer } : c);
      return localCustomers.find(c => c.id === id) || customer;
    }
  },
  async deleteCustomer(id: string) {
    localCustomers = localCustomers.filter(c => c.id !== id);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('customers').delete().eq('id', id);
    } catch {
      // fallback handled
    }
  },
  async bulkDeleteCustomers(ids: string[]) {
    localCustomers = localCustomers.filter(c => !ids.includes(c.id));
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('customers').delete().in('id', ids);
    } catch {
      // fallback handled
    }
  },
  async bulkUpdateCustomersStatus(ids: string[], status: string) {
    localCustomers = localCustomers.map(c => ids.includes(c.id) ? { ...c, status } : c);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('customers').update({ status }).in('id', ids);
    } catch {
      // fallback handled
    }
  },

  // Staff
  async getStaff(shopId?: string) {
    let targetShopId = shopId;
    if (!targetShopId) {
      const activeIds = await getActiveOwnerAndShopIds();
      targetShopId = activeIds.shopId;
    }

    if (!isSupabaseConfigured()) return localStaff;
    try {
      const { data, error } = await supabase.from('staff').select('*').eq('shop_id', targetShopId).order('created_at', { ascending: false });
      if (error) throw error;
      return data || [];
    } catch {
      return [];
    }
  },
  async addStaff(staff: any, shopId?: string) {
    const targetShopId = shopId || SHOP_ID;
    if (!isSupabaseConfigured()) {
      const newStaff = { ...staff, id: String(Date.now()), shop_id: targetShopId, created_at: new Date().toISOString() };
      localStaff = [newStaff, ...localStaff];
      return newStaff;
    }
    try {
      const { data, error } = await supabase.from('staff').insert([{ ...staff, shop_id: targetShopId }]).select().single();
      if (error) throw error;
      return data;
    } catch {
      const newStaff = { ...staff, id: String(Date.now()), shop_id: targetShopId, created_at: new Date().toISOString() };
      localStaff = [newStaff, ...localStaff];
      return newStaff;
    }
  },
  async updateStaff(id: string, staff: any, shopId?: string) {
    const targetShopId = shopId || SHOP_ID;
    if (!isSupabaseConfigured()) {
      localStaff = localStaff.map(st => st.id === id ? { ...st, ...staff } : st);
      return localStaff.find(st => st.id === id) || staff;
    }
    try {
      const { data, error } = await supabase.from('staff').update(staff).eq('id', id).select().single();
      if (error) throw error;
      return data;
    } catch {
      localStaff = localStaff.map(st => st.id === id ? { ...st, ...staff } : st);
      return localStaff.find(st => st.id === id) || staff;
    }
  },
  async deleteStaff(id: string) {
    localStaff = localStaff.filter(st => st.id !== id);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('staff').delete().eq('id', id);
    } catch {
      // fallback handled
    }
  },
  async bulkDeleteStaff(ids: string[]) {
    localStaff = localStaff.filter(st => !ids.includes(st.id));
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('staff').delete().in('id', ids);
    } catch {
      // fallback handled
    }
  },
  async bulkUpdateStaffStatus(ids: string[], status: string) {
    localStaff = localStaff.map(st => ids.includes(st.id) ? { ...st, status } : st);
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('staff').update({ status }).in('id', ids);
    } catch {
      // fallback handled
    }
  },

  // Shop Profile
  async getShop() {
    if (!isSupabaseConfigured()) return localShop;
    try {
      const { data, error } = await supabase.from('shops').select('*').eq('id', SHOP_ID).maybeSingle();
      if (error) throw error;
      
      if (!data) {
        // If the row doesn't exist, let's auto-provision it using upsert
        const { data: upsertData, error: upsertError } = await supabase.from('shops').upsert({ id: SHOP_ID, ...localShop }).select().single();
        if (upsertError) throw upsertError;
        return upsertData || localShop;
      }
      return data;
    } catch (err) {
      console.warn('Failed to fetch shop from Supabase, using local fallback:', err);
      return localShop;
    }
  },
  async updateShop(shop: any) {
    localShop = { ...localShop, ...shop };
    saveToLocalStorage('nexora_local_shop', localShop);
    if (!isSupabaseConfigured()) return localShop;
    try {
      // Clean up fields to avoid schema constraint issues (e.g. email_notifications_enabled)
      const { data, error } = await supabase.from('shops').upsert({ id: SHOP_ID, ...shop }).select().single();
      if (error) {
        console.warn('Upsert failed, retrying with schema-safe subset:', error);
        // Try again without potential non-existent columns (like email_notifications_enabled)
        const { email_notifications_enabled: _email_notifications_enabled, ...schemaSafeShop } = shop;
        const { data: retryData, error: retryError } = await supabase.from('shops').upsert({ id: SHOP_ID, ...schemaSafeShop }).select().single();
        if (retryError) throw retryError;
        return retryData;
      }
      return data;
    } catch (err) {
      console.error('Failed to update shop on Supabase:', err);
      return localShop;
    }
  },

  // Owner Profile
  async getProfile() {
    if (!isSupabaseConfigured()) return localProfile;
    try {
      const { data, error } = await supabase.from('profiles').select('*').eq('id', PROFILE_ID).maybeSingle();
      if (error) throw error;
      
      if (!data) {
        // If profile doesn't exist, auto-provision it using upsert
        const { data: upsertData, error: upsertError } = await supabase.from('profiles').upsert({ id: PROFILE_ID, ...localProfile }).select().single();
        if (upsertError) throw upsertError;
        return upsertData || localProfile;
      }
      return data;
    } catch (err) {
      console.warn('Failed to fetch profile from Supabase, using local fallback:', err);
      return localProfile;
    }
  },
  async updateProfile(profile: any) {
    localProfile = { ...localProfile, ...profile };
    saveToLocalStorage('nexora_local_profile', localProfile);
    if (!isSupabaseConfigured()) return localProfile;
    try {
      const { data, error } = await supabase.from('profiles').upsert({ id: PROFILE_ID, ...profile }).select().single();
      if (error) throw error;
      return data;
    } catch (err) {
      console.error('Failed to update profile on Supabase:', err);
      return localProfile;
    }
  }
};
